### ISSUE TITLE
When a user enters their zip code, a list of restrooms needs to be displayed

### ISSUE THREAD

**Issue by rluttmeratius** [jasekiw/ShameTheThrones#5]

**Comment by rluttmeratius** [comment]
We should break this down to two tasks - view and database

**Comment by rluttmeratius** [comment]
Should we have a zip code search bar on the landing page?

**Comment by travistme** [comment]
The thing about MVC is you create your model (which is used to get your data) and using it in your view (which displays your data). So, in my opinion it doesn't make much sense to break it into view and database. That may also be because I am just used to doing full stack work. But, we can talk it out.
